spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jwt_security
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
